data:
  class_path: src.datasets.data_modules.STPLSDataModule
  init_args:
    batch_size: 1
    num_workers: 48
    use_v2: false
    dataset_config:
      root_path: pcd_data/preprocessed_data/Synthetic_v3_InstanceSegmentation
      voxelize_only: true
      num_sampling_points: 4096
      quantization: 0.05
model:
  network:
    class_path: src.models.DynamicSAM
    init_args:
      pcd_encoder_params:
        trans_dim: 384
        depth: 12
        drop_path_rate: 0.1
        num_heads: 6
        group_size: 350
        num_group: 512
      prompt_encoder_params:
        embedding_dim: 384
      mask_decoder_params:
        trans_dim: 384
        num_multimask_outputs: 3
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 0.0001
      weight_decay: 0.05
  scheduler:
    class_path: torch.optim.lr_scheduler.MultiStepLR
    init_args:
      milestones: [890,990]
      gamma: 0.1
  # pcd_encoder_pretrain_path: work_dirs/ckpt-last-vitb-m0.8-d384-dec2.pth
  pcd_dump_interval: 600
  max_num_next_clicks: 20
  init_lr: 0.0001
  warmup_iter: 500
  iou_threshold: 0.5
  max_ious: [0.8, 0.85, 0.9]
  max_nocs: [1,2,3,5,10,15]
trainer:
  # max_epochs: 1000
  devices: [0]
  # check_val_every_n_epoch: 10
  # log_every_n_steps: 50
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
  logger:
    class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: experiments/seg_pcd/test/new_1
      name: stpls
ckpt_path: path/to/checkpoint